XML file links, exception handling, better img integration support.
shauryauppal/PyWhatsapp pull request #76
Opened 2020-11-19 17:57 UTC by phanicode

2020-11-19 18:16 UTC, shauryauppal requested changes
Request some minor changes. The rest looks good. Thanks for contributing to open source. :-)

2020-11-19 18:16 UTC, shauryauppal commented on PyWhatsapp.py
> +
Why so much spacing in code here?

2020-11-19 18:16 UTC, shauryauppal commented on PyWhatsapp.py
> +
Here also can we remove spacing or keep it to one line

2020-11-19 18:16 UTC, shauryauppal commented on PyWhatsapp.py
> +    # modified code to work with my particular implementation
Cool got it can we remove these comments, don't want this to go to production.

2020-11-19 18:16 UTC, shauryauppal commented on PyWhatsapp.py
> +                    # No need to print File not sent as try except statements are in function.
Please remove the comment here and below

2020-11-19 18:30 UTC, shauryauppal approved these changes

2020-11-19 18:31 UTC, merged

2020-11-19 18:32 UTC, shauryauppal commented
Congrats @phanicode on officially being part of PyWhatsapp as a Contributor.

2022-08-16 07:28 UTC, khale11 commented
Hi مرحبا